server:
  port: 8090
spring:
  application:
    name: zipkinclient
  sleuth:
    web:
      enabled: true
    sampler: 1.0
  zipkin: http://localhost:9090/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
