server:
  port: 8762
spring:
  devtools:
    add-properties: false
  application:
    name: native-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
